server:
  port: 8761


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #表示是否注册自身到eureka服务器
    fetchRegistry: false #表示是否从eureka服务器获取注册信息
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #设置eureka服务器所在的地址

#指定进行服务注册时该服务的名称
spring:
  application:
    name: eurka-server